name: "JAVA CI with Maven"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x86
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temarin'
          # anchitecture: x64
      - name: Build with Maven
        run: mvn -B package --file pom.xml